apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name | trunc 63 | trimSuffix "-" }}-deployment
spec:
  replicas: {{ .Values.replicas | default "1" }}
  strategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.name | trunc 63 | trimSuffix "-" }}
  template:
    metadata:
      annotations:
        git-commit_sha: {{ .Values.global.commit_sha | required "O argumento 'commit_sha' é obrigatório" | quote }}
      labels:
        app: {{ .Values.name | trunc 63 | trimSuffix "-" }}
    spec:
      {{- if hasKey .Values "volumes" }}
      volumes:
      {{- range $k, $v := .Values.volumes }}
        - name: {{ $v.name }}-{{ $.Values.login | trunc 63 | trimSuffix "-" }}
          persistentVolumeClaim:
            claimName: {{ $v.name }}-{{ $.Values.login | trunc 63 | trimSuffix "-" }}-pvc
      {{- end }}
      {{- end }}
      containers:
      - name: {{ .Values.name | trunc 63 | trimSuffix "-" }}
        image: {{ .Values.image | default "nginx:latest" }}
        ports:
        - containerPort: {{ .Values.containerPort }}
        resources:
          limits:
            memory: {{ .Values.resources.memory | quote }}
          requests:
            memory: {{ .Values.resources.memory | quote }}
        {{- if hasKey .Values "volumes" }}
        volumeMounts:
        {{- range $k, $v := .Values.volumes }}
            - name: {{ $v.name }}-{{ $.Values.login | trunc 63 | trimSuffix "-" }}
              mountPath: {{ $v.path | trimSuffix "-" }}
        {{- end }}
        {{- end }}
        {{- if hasKey .Values "environments" }}
        envFrom:
          - configMapRef:
              name: {{ .Values.name | trunc 63 | trimSuffix "-" }}-configmap
        {{- end }}
        {{- if hasKey .Values "livenessProbe"}}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if hasKey .Values "readinessProbe"}}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if hasKey .Values "startupProbe"}}
        startupProbe:
          {{- toYaml .Values.startupProbe | nindent 10 }}
        {{- end }}

