apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.name | trunc 63 | trimSuffix "-" }}-job-{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | trunc 5 }}-{{ .Values.global.commit_sha | toString | trunc 5 }}
spec:
  completions: 1
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        git-commit_sha: {{ .Values.global.commit_sha | required "O argumento 'commit_sha' é obrigatório" | quote }}
    spec:
      {{- if hasKey .Values "volumes" }}
      volumes:
      {{- range $k, $v := .Values.volumes }}
        - name: {{ $v.name }}-{{ $.Values.login | trunc 63 | trimSuffix "-" }}
          persistentVolumeClaim:
            claimName: {{ $v.name }}-{{ $.Values.login | trunc 63 | trimSuffix "-" }}-pvc
      {{- end }}
      {{- end }}
      initContainers:
      - name: init-container
        image: alpine:3.22
        command: ['sh', '-c', {{ printf "'%s'" (.Values.commandInitContainer | default "echo Init Container Executed") }}]
        resources:
          limits:
            memory: {{ .Values.resources.memory | quote }}
          requests:
            memory: {{ .Values.resources.memory | quote }}
        {{- if hasKey .Values "volumes" }}
        volumeMounts:
        {{- range $k, $v := .Values.volumes }}
            - name: {{ $v.name }}-{{ $.Values.login | trunc 63 | trimSuffix "-" }}
              mountPath: {{ $v.path | trimSuffix "-" }}
        {{- end }}
        {{- end }}
        {{- if hasKey .Values "environments" }}
        envFrom:
          - configMapRef:
              name: {{ .Values.name | trunc 63 | trimSuffix "-" }}-configmap
        {{- end }}
      restartPolicy: OnFailure
      containers:
      - name: {{ .Values.name | trunc 63 | trimSuffix "-" }}
        image: {{ .Values.image | default "alpine:3.22" }}
        resources:
          limits:
            memory: {{ .Values.resources.memory | quote }}
          requests:
            memory: {{ .Values.resources.memory | quote }}
        {{- if hasKey .Values "volumes" }}
        volumeMounts:
        {{- range $k, $v := .Values.volumes }}
            - name: {{ $v.name }}-{{ $.Values.login | trunc 63 | trimSuffix "-" }}
              mountPath: {{ $v.path | trimSuffix "-" }}
        {{- end }}
        {{- end }}
        {{- if hasKey .Values "environments" }}
        envFrom:
          - configMapRef:
              name: {{ .Values.name | trunc 63 | trimSuffix "-" }}-configmap
        {{- end }}
